### ISSUE TITLE
VAPIX-access-for-ACAP-applications runtime credentials work with local RTSP endpoint or only http?

### ISSUE THREAD

**Issue by mms-** [AxisCommunications/acap-documentation#113]
Do the runtime credentials also give us access to the RTSP server? Have not yet tested this, if not then please add this. Otherwise we still need to ask clients to enter a username/password upon app installation on the camera. This is an inconvenience which lowers adoption and long term stability of the app. Our app uses the local RTSP server and for the sake of efficiency we do not want to duplicate this functionality inside our app.

Thank you.

**Comment by mms-** [comment]
Hi, thank you for the reply. By RTSP over http you mean over the WebSocket connection?

Also for older camera firmware that does not support the runtime user credentials, will the same app still function on these systems? I.e. with the removed user section in the manifest file?

Thank you.

**Comment by mms-** [comment]
Does not work! How to do proper rtsp over websocket? 

Using runtime creds to connect to ws://127.0.0.12:80/rtsp-over-websocket always yields 401 in our test. If anonymous viewing is enabled the connection does work.

Also tried the /rtsp-over-websocket?/rtspwssession=token method same result. 
We are able to get a token using the runtime creds from /axis-cgi/rtspwssession.cgi 

/rtsp-over-websocket isn't documented anywhere does it work? What is the proper way to get to the rtsp stream over http? 

/rtsp-over-websocket on 127.0.0.1 with root credentials does work so it is supported. Why are runtime creds not supported?

We are unable to release our ACAP due to this.

**Comment by deepikas20** [comment]
Hi! I would check and get back to you asap.

**Comment by deepikas20** [comment]
Hi! We have fixed some issues since January. Could you please try  rtspwssession=token on 127.0.0.1 using runtime credentials?
