### ISSUE TITLE
The name of the default branch

### ISSUE THREAD

**Issue by mattias-kindborg-at-work** [AxisCommunications/acap-documentation#18]
The name of the default branch is `master`. We ought to discuss the pros and cons for keeping this name in favour of `main`.

The following arguments are opposed to naming the default branch `master`.

- Inclusiveness
- This is a new project, thus I assumed the default branch to be `main`
- With time, the name `master` will be used more seldom. New project will be created with the name `main` and many old project will probably migrate to the new name `main`

The following arguments are favouring the default branch `master`.

- Most developers today will recognise the name `master`, but an argument can be made that this will transition to be false given time
- Given you're using links to reference specific parts of this repository from parts of the internet, the risks are high that the default branch name is part of these links.

**Comment by pataxis** [comment]
This will be switched in connection with next SDK release

**Comment by mattias-kindborg-at-work** [comment]
This has now been completed, default branch is now called `main`.
