### ISSUE TITLE
Reference in "Application project structure"

### ISSUE THREAD

**Issue by mattias-kindborg-at-work** [AxisCommunications/acap-documentation#25]
In the table describing the manifest file content, there's a reference attached to the parameter called `acapPackageConf.setup.embeddedSdkVersion`. The reference is assumed to be found under the table, but is instead found at the end of the document, under a chapter called *Local data*.

**Comment by pataxis** [comment]
We're using Markdown footnotes to get numbered links. Unfortunately I haven's seen a way to place the footnotes in other places but the end of the page. If there is it would be great, please reopen with a suggestion.
