### ISSUE TITLE
Markdownlint for GitHub CI pipeline?

### ISSUE THREAD

**Issue by joakimr-axis** [AxisCommunications/acap-documentation#37]
I cannot find markdownlint being run for the markdown files in the GitHub pipeline, am I missing something or is it indeed missing?

**Comment by mikaelli-axis** [comment]
We are looking to do this but haven't gotten around to it yet.

**Comment by mattias-kindborg-at-work** [comment]
We'll soon have Markdown linting setup for this project. We chose to start with Markdown since this is a repository where Markdown files are of most value. Further on we'll add linters for new file types.

Thank you very much @joakimr-axis for reporting this issue!
