### ISSUE TITLE
Mention lack of support for signing using older SDKs

### ISSUE THREAD

**Issue by jojju** [AxisCommunications/acap-documentation#66]
We have gotten the feedback that we ought to state in the documentation that applications built using older SDKs cannot be signed in the ACAP portal. This is relevant for ACAP3 SDK versions below 3.5 and Native SDK versions below 1.1.

The reason for this is that the portal requires "architecture" to be included in the manifest, and support for that did not exist in earlier SDKs.

**Comment by FantasticFiasco** [comment]
Ok, we'll look into it!

**Comment by mattias-kindborg-at-work** [comment]
Ok, we'll look into it.
