### ISSUE TITLE
Why 2 version tracks (version 1.x vs  4.x) referred to in ACAP Native SDK documentation

### ISSUE THREAD

**Issue by chrisson-axis** [AxisCommunications/acap-documentation#91]
Hi,

Why are we referring to 2 different versions tracks in our official **_ACAP Native SDK  documentation_**, i.e. version 1.x track and version 4.x track?

This just causes confusion, why not only refer to 4.x versions in all places?

See this page:

https://axiscommunications.github.io/acap-documentation/docs/api/native-sdk-api.html#compatibility

<h2 id="compatibility" style="box-sizing: border-box; margin-top: 1.5em; margin-bottom: 0.25em; font-weight: 500; line-height: 1.25; color: rgb(51, 51, 51); font-size: 24px !important; position: relative; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Compatibility</h2><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1em; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The table below shows ACAP Native SDK and firmware version compatibility.</p><div class="table-wrapper" style="box-sizing: border-box; margin-top: 0.5em; display: block; width: 736.023px; max-width: 100%; margin-bottom: 1.5rem; overflow-x: auto; border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 2px, rgba(0, 0, 0, 0.08) 0px 3px 10px; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

SDK version | Available from firmware version
-- | --
1.0 | 10.7
1.1 | 10.9
1.2 | 10.10
1.3 | 10.12
1.4 | 11.0
1.5 | 11.1
1.6 | 11.2
1.7 | 11.3

</div>

....and compare it to this one: 

https://axiscommunications.github.io/acap-documentation/docs/axis-devices-and-compatibility/#find-the-right-sdk-for-software-compatibility

<h2 id="find-the-right-sdk-for-software-compatibility" style="box-sizing: border-box; margin-top: 1.5em; margin-bottom: 0.25em; font-weight: 500; line-height: 1.25; color: rgb(51, 51, 51); font-size: 24px !important; position: relative; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Find the right SDK for software compatibility</h2><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1em; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Choose the appropriate SDK version based on what AXIS OS version you want supporting your ACAP.</p><div class="table-wrapper" style="box-sizing: border-box; margin-top: 0.5em; display: block; width: 736.023px; max-width: 100%; margin-bottom: 1.5rem; overflow-x: auto; border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 2px, rgba(0, 0, 0, 0.08) 0px 3px 10px; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

ACAP SDK version | Compatible with AXIS OS version
-- | --
SDK 4.0 | 10.7 and later
SDK 4.1 | 10.9 and later
SDK 4.2 | 10.10 and later
SDK 4.3 | 10.12 and later
SDK 4.4 | 11.0 and later
SDK 4.5 | 11.1 and later
SDK 4.6 | 11.2 and later
SDK 4.7 | 11.3 and later

</div>

Is there any particular benefit of mentioning 1.x versions at all?

**Comment by pataxis** [comment]
Hi @chrisson-axis it does look a bit mixed up and we'll look in to improve this.

## Version explanation

The idea is to separate the offering `ACAP 4.X` which contains various artifacts where `ACAP Native SDK 1.X` is one of them.
An example here in the [ACAP 4.7 release notes](https://axiscommunications.github.io/acap-documentation/docs/release-notes/4.7.html#overview).

The SDK image `acap-native-sdk` is a new product and thus starts on 1.0 (as opposed to previous image `acap-sdk`).

### ACAP 3
acap-sdk 3.X

### ACAP 4
acap-native-sdk 1.X
acap-computer-vision-sdk 1.X

**Comment by mattias-kindborg-at-work** [comment]
Closed due to inactivity

**Comment by mattias-kindborg-at-work** [comment]
Opened due to misunderstanding of the issue
